### PR TITLE
Custom Error Messages, Custom Attributes

### PR DESCRIPTION
**Pull request by moura137**
Added the properties  and  with methods Getters and Setters, for options of Custom Error Messages, Custom Attributes

### CODE REVIEW

**Comment by ghost** [comment]
:+1: 

should update readme too

**Comment by ghost** [comment]
any updates on this? i kinda need it :)

**Comment by emnsen** [comment]
:+1:

**Comment by ghost** [comment]
maybe add a new release tag with these changes?

**Pull request merged**
