### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:information_source: Shift detected you do not have a CI workflow using GitHub Actions. If you would like, Shift can help you get started with the [CI Generator](https://laravelshift.com/ci-generator). Although the Shift is paid, GitHub Actions is free and having a CI workflow will improve the stability and review process for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-validator.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "prettus/laravel-validation": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Review by iEgria — APPROVED** [review]

**Comment by gabrielboliveira** [comment]
Hey @andersao hope all is well!

This PR is pending to also update the [andersao/l5-repository](https://github.com/andersao/l5-repository).

Are you able to take a look on it and perhaps merge and tag it? Then I might be able to open the update PR for the l5-repository.

**Comment by uar-goran-grbic** [comment]
@gabrielboliveira @andersao This probably should go into version ^2 with minimal PHP requirement of `>=8.2` and Illuminate packages to support `^10.0|^11.0` only. Older Laravel versions (i.e. v9) are deprecated now. Security fixes for v10 will be due beginning of 2025.

**Review by nchingoski — APPROVED** [review]

**Comment by nikalemdzievski** [comment]
Hey @andersao! Any chance this can be merged any time soon?

**Review by scod — APPROVED** [review]

**Review by Remcojansen88 — APPROVED** [review]

**Review by Remcojansen88 — APPROVED** [review]

**Review by BERKHASSEKAOUTAR — APPROVED** [review]
I approve these changes

**Pull request merged**
